"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from os import environ  # to manage the environment variables directly
# to load environment variables from a `.env` file.
from dotenv import load_dotenv
from datetime import timedelta  # for the JWT duration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Looks for `DJANGO_ENV` in the environment, defaults to 'dev' when not found
env_type = environ.get('DJANGO_ENV', 'dev')
# Set name of file with environment variables
env_file = BASE_DIR / f'.env.{env_type}'
# Only load .env file if it exists (for local development)
# In Docker, environment variables are passed directly
if env_file.exists():
    load_dotenv(env_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# choose between DEBUG (dev) mode or not (for production)
DEBUG = environ.get('DJANGO_DEBUG', "False").lower() == "true"


def _split_env_list(env_name: str, default: str = "") -> list[str]:
    """Read comma-separated env var values and drop empty entries."""
    return [item.strip() for item in environ.get(env_name, default).split(",")
            if item.strip()]


# keep list of allowed hosts in the environment (only localhost for dev)
ALLOWED_HOSTS = _split_env_list('DJANGO_ALLOWED_HOSTS', 'localhost')

# Application definition
# TODO: install drf-spectacular and implement automatic openapi schemas and
# typescript interfaces
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    # 'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'core',
    'accounts',
    'recipes',
    'ingredients',
    'animes',
]

REST_FRAMEWORK: dict[str, list[str]] = {
    # TODO: configue pagination
    #     "DEFAULT_PAGINATION_CLASS":
    #         "rest_framework.pagination.PageNumberPagination",
    #     "PAGE_SIZE": 10,
    # To choose a default permission if none is provided explicitly for a
    # view
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAdminUser",
        # isAdminUser refers to is_staff not to is_superuser
    ],
}

# Disable browsable API when in production:
if DEBUG:
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] = [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ]
    REST_FRAMEWORK["DEFAULT_AUTHENTICATION_CLASSES"] = [
        # read token from cookies and write it into them (good for browser
        # SPAs):
        "accounts.authentication.CookieJWTAuthentication",
        # read cookies from the header (Authorization Bearer token), useful
        # for mobile apps:
        # "rest_framework_simplejwt.authentication.JWTAuthentication",
        # "rest_framework.authentication.SessionAuthentication",
    ]
else:
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] = [
        "rest_framework.renderers.JSONRenderer",
    ]
    REST_FRAMEWORK["DEFAULT_AUTHENTICATION_CLASSES"] = [
        # read token from cookies and write it into them (good for browser
        # SPAs):
        "accounts.authentication.CookieJWTAuthentication",
        # read cookies from the header (Authorization Bearer token), useful
        # for mobile apps:
        # "rest_framework_simplejwt.authentication.JWTAuthentication",
    ]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "UPDATE_LAST_LOGIN": True,  # default: False. Serves to update last_login
                                # default user field
    # TODO: implement rotating refresh tokens (necessitates the blacklist app)
    "ROTATE_REFRESH_TOKENS": False,  # default: False
    "BLACKLIST_AFTER_ROTATION": False,  # default: False
    "CHECK_USER_IS_ACTIVE": True,  # default: True
}

CORS_ALLOWED_ORIGINS = _split_env_list(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173',
)

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = _split_env_list(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173',
)

# Auth cookie behavior can be overridden per environment. This is useful for
# temporary pseudo-production deployments without HTTPS.
AUTH_COOKIE_SECURE = environ.get(
    'DJANGO_AUTH_COOKIE_SECURE',
    str(not DEBUG),
).lower() == "true"
AUTH_COOKIE_SAMESITE = environ.get('DJANGO_AUTH_COOKIE_SAMESITE', 'Lax')

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Configuration for a sqlite database:
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Configuration for postgresql database
# TODO: add TEST database configuration (test database may be a mirror from
# the main one, migration may be configured too)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': environ.get('DB_NAME'),
        'USER': environ.get('DB_USER'),
        'PASSWORD': environ.get('DB_PW'),
        'HOST': environ.get('DB_HOST'),
        'PORT': environ.get('DB_PORT'),
    }
}

AUTH_USER_MODEL = 'accounts.CustomUser'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.'
        'UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
        'MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
        'CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
        'NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# local french time
TIME_ZONE = 'Europe/Paris'  # originally UTC

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Directory where `collectstatic` gathers all static files for production.
# Nginx serves this directory directly instead of Django.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user-uploaded content)
# https://docs.djangoproject.com/en/6.0/topics/files/

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Instructions to migrate to S3 made by AI:
# --- Production file storage (S3) ---
# To switch from local filesystem to S3:
#   1. uv add django-storages[s3]
#   2. Add 'storages' to INSTALLED_APPS
#   3. Uncomment the block below and configure env vars:
#
# STORAGES = {
#     "default": {
#         "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
#     },
#     "staticfiles": {
#         "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
#     },
# }
# AWS_STORAGE_BUCKET_NAME = environ.get('AWS_STORAGE_BUCKET_NAME')
# AWS_S3_REGION_NAME = environ.get('AWS_S3_REGION_NAME')
# AWS_ACCESS_KEY_ID = environ.get('AWS_ACCESS_KEY_ID')
# AWS_SECRET_ACCESS_KEY = environ.get('AWS_SECRET_ACCESS_KEY')
# AWS_S3_CUSTOM_DOMAIN = environ.get('AWS_S3_CUSTOM_DOMAIN')  # e.g. CDN
# AWS_QUERYSTRING_AUTH = False  # public-read bucket
